"""add new columns and datatype for the assetvariant table

Revision ID: 220b49792ebc
Revises: 5bb210ca3f0e
Create Date: 2026-05-05 11:26:21.427284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220b49792ebc'
down_revision: Union[str, Sequence[str], None] = '5bb210ca3f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_variants', sa.Column('variant_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint(op.f('asset_variants_asset_id_fkey'), 'asset_variants', type_='foreignkey')
    op.create_foreign_key(None, 'asset_variants', 'assets', ['asset_id'], ['id'])
    op.drop_column('asset_variants', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_variants', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'asset_variants', type_='foreignkey')
    op.create_foreign_key(op.f('asset_variants_asset_id_fkey'), 'asset_variants', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.drop_column('asset_variants', 'variant_id')
    # ### end Alembic commands ###
