"""add search vector to documents

Revision ID: 4e8ea87fe2be
Revises: 95ed9c490f28
Create Date: 2026-05-02 05:17:29.621349

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e8ea87fe2be"
down_revision: Union[str, Sequence[str], None] = "95ed9c490f28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(ocr_text, ''))", persisted=True
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_assets_search_vector",
        "assets",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_assets_search_vector", table_name="assets", postgresql_using="gin"
    )
    op.drop_column("assets", "search_vector")
    # ### end Alembic commands ###
