"""add asset variant table

Revision ID: 5bb210ca3f0e
Revises: 4e8ea87fe2be
Create Date: 2026-05-04 10:22:18.162167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb210ca3f0e'
down_revision: Union[str, Sequence[str], None] = '4e8ea87fe2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_variants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(
    ['asset_id'],
    ['assets.id'],
    ondelete='CASCADE'
),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_variants_asset_id'), 'asset_variants', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_variants_created_at'), 'asset_variants', ['created_at'], unique=False)
    op.create_index(op.f('ix_asset_variants_s3_key'), 'asset_variants', ['s3_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_variants_s3_key'), table_name='asset_variants')
    op.drop_index(op.f('ix_asset_variants_created_at'), table_name='asset_variants')
    op.drop_index(op.f('ix_asset_variants_asset_id'), table_name='asset_variants')
    op.drop_table('asset_variants')
    # ### end Alembic commands ###
