"""add size_bytes to assets

Revision ID: 95ed9c490f28
Revises: 4c0731ee3da0
Create Date: 2026-04-30 13:08:35.372690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ed9c490f28'
down_revision: Union[str, Sequence[str], None] = '4c0731ee3da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'size_bytes')
    # ### end Alembic commands ###
