"""fix variant_id autoincrement

Revision ID: b989443b90fe
Revises: 220b49792ebc
Create Date: 2026-05-05 11:51:48.720115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b989443b90fe'
down_revision: Union[str, Sequence[str], None] = '220b49792ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS asset_variants_variant_id_seq")
    op.execute("ALTER TABLE asset_variants ALTER COLUMN variant_id SET DEFAULT nextval('asset_variants_variant_id_seq')")
    op.execute("ALTER SEQUENCE asset_variants_variant_id_seq OWNED BY asset_variants.variant_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
